# Header
menu:
  主页: /
  骑行: /ride
  摄影: /photography
  比赛: /match
  链接: /links
  关于: /about
# logo: https://qiniu.miiiku.xyz/src/images/logo.png
banner: http://c2.biketo.com/d/file/news/girl/2020-03-07/e2e473dd266aab28bb4d5e37f7692496.jpg
# banner: css/images/banner.jpg

# large cover
# long: [article, links]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: true
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
valine:
  enable: true
  appId: 
  appKey: 
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: true
  visitor: true
  pageSize: 10

disqus:
  enable: true
  website: heybreeze.cn
  error: 如果你看不到评论，那么就真的看不到评论了 QAQ

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall:
  enable: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
# Specific configuration information go to `layout/plug-in/zoom.ejs`
zoom:
  enable: true


# widget behavior
archive_type: 'monthly'
show_count: true

# beian
beian: 

# Miscellaneous
google_analytics: 
gauges_analytics: 
baidu_analytics: 
tencent_analytics: 
favicon: /favicon.ico


# Social Icon
social_icon:
  header_enable: true
  footer_enable: true
  icons:
    - { type: email,      value: thelovelybugfly@foxmail.com }
    - { type: github,     value: https://github.com/HeyBreezeYang }
    - { type: google+,    value: https://www.google.com }
    - { type: ins,        value: https://www.instagram.com/thelovelybugfly }
    - { type: twitter,    value: https://twitter.com/thelovelybugfly }
    - { type: youtube,    value: https://www.youtube.com }
    - { type: weibo,      value: https://weibo.com/6460014012/profile?topnav=1&wvr=6 }
    - { type: cloudmusic, value: https://music.163.com/#/user/home?id=1364962893 }
    - { type: zhihu,      value: https://www.zhihu.com }
